### ISSUE TITLE
Turn relays off

### ISSUE THREAD

**Issue by proautodinc** [kanesurendra/echo-pi#1]
Thanks for sharing this script, it is exactly what I was looking for to control a 16 relay board.

I'm having a problem turning the relays off, Using Alexa I can turn the relays on, but not off. It returns:
```
DEBUG:root:Responding to OFF for gpio2
State False on gpio2 from client @ 192.168.0.143 gpio port:  2
('port: %d , state: %s', 2, False)
```

Any idea why?

Thanks.

**Comment by kanesurendra** [comment]
I have tested the script and works for me. Is this a problem only for gpio2 turning off?

**Comment by proautodinc** [comment]
Hi, thanks for repluing. No, all of them, I'm using a 16 relay board, I can
turn all of them on using alexa comand , but not off,

**Comment by proautodinc** [comment]
If I move the cable from pin 1 (5v) to pin 2 (3.3v) in the raspberry pi, the script works but backwards, If I ask Alexa to turn off, it turns on, and I if ask to turn on it turns off.

**Comment by proautodinc** [comment]
Moving the Pin 1(5v) to Pin 2(3.3v) on the raspberry Pi solve my problem.

**Comment by kanesurendra** [comment]
Ok. So its resolved then?

**Comment by proautodinc** [comment]
Yes, nothing wrong with your script. Thank you. But I got a question. After Alexa discover all the gpio, I can turn them on and off just saying "Alexa turn on/off gpio2", but if I group all of them in the Alexa app and name it for exampe: Home, whem I say "Alexa turn on/off home" I can see that the script is running through all of the gpio ports but only 4 or 5 worked, it skips some ports and it does that randomly.
